version: "3.7"

services:
  db:
    image: postgres:16
    container_name: postgres_app
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - athkeeper_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    restart: always
    expose:
      - 6379

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: athkeeper_app
    command: sh -c "alembic upgrade 311247e40726 && cd src && uvicorn main:app --host=0.0.0.0 --port=8000"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    container_name: celery_app
    env_file:
      - .env
    command: sh -c "cd src && celery -A tasks.tasks:celery worker --loglevel=INFO"
    restart: always
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    env_file:
      - .env
    command: sh -c "cd src && celery -A tasks.tasks:celery beat"
    restart: always
    depends_on:
      - redis
      - celery

volumes:
  athkeeper_data:
