"""added bif buy

Revision ID: 3b39e49f6a68
Revises: 146d832ad29e
Create Date: 2024-03-24 17:50:45.884548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b39e49f6a68'
down_revision: Union[str, None] = '146d832ad29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bif_buy_1', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('bif_buy_2', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('bif_buy_3', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bif_buy_3')
    op.drop_column('user', 'bif_buy_2')
    op.drop_column('user', 'bif_buy_1')
    # ### end Alembic commands ###
