"""creating db

Revision ID: e77d1aec8849
Revises: 
Create Date: 2024-03-25 09:33:29.631818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77d1aec8849'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_error_msgs',
    sa.Column('error_msg', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_error_msgs_id'), 'trade_error_msgs', ['id'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('for_free', sa.Boolean(), nullable=False),
    sa.Column('ban', sa.Boolean(), nullable=False),
    sa.Column('mexc_api_key', sa.String(), nullable=True),
    sa.Column('mexc_secret_key', sa.String(), nullable=True),
    sa.Column('auto_trade', sa.Boolean(), nullable=False),
    sa.Column('trade_quantity', sa.Integer(), nullable=False),
    sa.Column('trade_percent', sa.Float(), nullable=False),
    sa.Column('symbol_to_trade', sa.String(), nullable=False),
    sa.Column('bif_is_active', sa.Boolean(), nullable=False),
    sa.Column('bif_percent_1', sa.Float(), nullable=False),
    sa.Column('bif_percent_2', sa.Float(), nullable=False),
    sa.Column('bif_percent_3', sa.Float(), nullable=False),
    sa.Column('bif_price_1', sa.Float(), nullable=True),
    sa.Column('bif_price_2', sa.Float(), nullable=True),
    sa.Column('bif_price_3', sa.Float(), nullable=True),
    sa.Column('bif_buy_1', sa.Boolean(), nullable=False),
    sa.Column('bif_buy_2', sa.Boolean(), nullable=False),
    sa.Column('bif_buy_3', sa.Boolean(), nullable=False),
    sa.Column('last_paid', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('trade',
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('buy_quantity', sa.Float(), nullable=True),
    sa.Column('cummulative_qoute_qty', sa.Float(), nullable=True),
    sa.Column('buy_order_id', sa.String(length=50), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('sell_order_id', sa.String(length=50), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_id'), 'trade', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_id'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trade_error_msgs_id'), table_name='trade_error_msgs')
    op.drop_table('trade_error_msgs')
    # ### end Alembic commands ###
